/**
 * ============================================================
 * GLOSSÁRIO DE TERMOS HARMÔNICOS
 * ============================================================
 */

export type NivelTermo = 'iniciante' | 'intermediario' | 'avancado';

export type CategoriaGlossario = 'notas-basicas' | 'intervalos' | 'acordes' | 'funcao-harmonica' | 'escalas' | 'estilos' | 'teoria-avancada';

export interface TermoGlossario {
  id: string;
  termo: string;
  termoIngles?: string;
  simbolo?: string;
  nivel: NivelTermo;
  categoria: CategoriaGlossario;
  definicaoSimples: string;
  definicaoCompleta: string;
  exemplos: string[];
  exemplosMusicas?: string[];
  termosRelacionados: string[];
  tooltipTexto: string;
  curiosidade?: string;
}

export const GLOSSARIO: TermoGlossario[] = [
  // NOTAS
  { id: 'nota', termo: 'Nota', nivel: 'iniciante', categoria: 'notas-basicas', definicaoSimples: 'Um som musical com altura definida, como Dó, Ré, Mi.', definicaoCompleta: 'Uma nota é um som com frequência específica. No sistema ocidental, usamos 12 notas cromáticas: C, C#, D, D#, E, F, F#, G, G#, A, A#, B.', exemplos: ['C (Dó)', 'A4 = 440 Hz'], termosRelacionados: ['oitava', 'semitom'], tooltipTexto: 'Som com altura definida (Dó, Ré, Mi...)', curiosidade: 'A4 = 440 Hz é o padrão internacional de afinação desde 1939.' },
  { id: 'semitom', termo: 'Semitom', termoIngles: 'Half step', nivel: 'iniciante', categoria: 'intervalos', definicaoSimples: 'A menor distância entre duas notas — de uma tecla para a vizinha.', definicaoCompleta: 'O semitom é a menor unidade de distância no sistema temperado. No piano, é a distância entre qualquer tecla e sua vizinha.', exemplos: ['C → C# = 1 semitom', 'E → F = 1 semitom', 'B → C = 1 semitom'], termosRelacionados: ['tom', 'intervalo'], tooltipTexto: 'Menor distância entre duas notas (1 tecla no piano)' },
  { id: 'tom', termo: 'Tom', termoIngles: 'Whole step', nivel: 'iniciante', categoria: 'intervalos', definicaoSimples: 'Dois semitons. A distância entre C e D.', definicaoCompleta: 'Um tom = 2 semitons. Base da escala diatônica maior: T-T-S-T-T-T-S.', exemplos: ['C → D = 1 tom', 'F → G = 1 tom'], termosRelacionados: ['semitom', 'intervalo'], tooltipTexto: 'Dois semitons (distância C→D)' },
  { id: 'oitava', termo: 'Oitava', termoIngles: 'Octave', nivel: 'iniciante', categoria: 'intervalos', definicaoSimples: 'A mesma nota em registro mais agudo ou grave — dobro da frequência.', definicaoCompleta: 'Intervalo de 12 semitons. Proporção 2:1. C4→C5 = oitava.', exemplos: ['C4 → C5', '440 Hz → 880 Hz'], termosRelacionados: ['nota', 'intervalo'], tooltipTexto: 'Mesma nota em registro diferente (2× frequência)', curiosidade: 'Tão consonante que parece a mesma nota.' },
  { id: 'enarmonia', termo: 'Enarmonia', termoIngles: 'Enharmonic', nivel: 'iniciante', categoria: 'notas-basicas', definicaoSimples: 'Dois nomes para o mesmo som: C# = Db.', definicaoCompleta: 'Notas enarmônicas produzem o mesmo som mas têm nomes diferentes conforme o contexto harmônico.', exemplos: ['C# = Db', 'F# = Gb', 'B = Cb'], termosRelacionados: ['nota', 'semitom'], tooltipTexto: 'Dois nomes para o mesmo som (C# = Db)' },
  // INTERVALOS
  { id: 'intervalo', termo: 'Intervalo', termoIngles: 'Interval', nivel: 'iniciante', categoria: 'intervalos', definicaoSimples: 'A distância entre duas notas, medida em semitons.', definicaoCompleta: 'Pode ser melódico (sequencial) ou harmônico (simultâneo). Nomeado por número e qualidade (maior, menor, justa).', exemplos: ['C → E = 3ª maior (4 st)', 'C → G = 5ª justa (7 st)'], termosRelacionados: ['semitom', 'terca', 'quinta'], tooltipTexto: 'Distância entre duas notas em semitons' },
  { id: 'terca', termo: 'Terça', termoIngles: 'Third', nivel: 'iniciante', categoria: 'intervalos', definicaoSimples: 'Intervalo de 3 ou 4 semitons — define se o acorde é maior ou menor.', definicaoCompleta: '3ª menor = 3 st (som menor), 3ª maior = 4 st (som maior). Acordes são empilhamento de terças.', exemplos: ['C→E = 3M → maior', 'C→Eb = 3m → menor'], termosRelacionados: ['quinta', 'triade'], tooltipTexto: '3ª menor (3 st) ou maior (4 st) — define maior/menor' },
  { id: 'quinta', termo: 'Quinta', termoIngles: 'Fifth', nivel: 'iniciante', categoria: 'intervalos', definicaoSimples: 'Intervalo de 7 semitons — presente em quase todos os acordes.', definicaoCompleta: '5ª justa (7 st) = mais estável após oitava. 5ª diminuta (6 st) = trítono. 5ª aumentada (8 st) = acorde aumentado.', exemplos: ['C→G = 5J', 'B→F = 5d (trítono)'], termosRelacionados: ['tritono', 'triade'], tooltipTexto: '5ª justa = 7 semitons, em quase todos os acordes' },
  { id: 'setima', termo: 'Sétima', termoIngles: 'Seventh', nivel: 'iniciante', categoria: 'intervalos', definicaoSimples: 'O 4º grau adicionado a uma tríade, criando tétrades ricas.', definicaoCompleta: '7ª menor (10 st) → dominante. 7ª maior (11 st) → maj7. 7ª diminuta (9 st) → dim7.', exemplos: ['C→Bb = 7m → C7', 'C→B = 7M → Cmaj7'], termosRelacionados: ['tetrade', 'dominante'], tooltipTexto: '4ª nota da tétrade: menor (C7) ou maior (Cmaj7)' },
  { id: 'tritono', termo: 'Trítono', termoIngles: 'Tritone', nivel: 'intermediario', categoria: 'intervalos', definicaoSimples: 'O intervalo mais tenso — 6 semitons, metade da oitava.', definicaoCompleta: '4ª aumentada ou 5ª diminuta. Todo acorde V7 contém um trítono entre a 3ª e 7ª. "Diabolus in musica".', exemplos: ['C→F# = trítono', 'G7: B→F = trítono interno'], termosRelacionados: ['dominante', 'substituicao-tritono'], tooltipTexto: '6 semitons — o intervalo mais tenso', curiosidade: '"Diabolus in musica" — proibido na Idade Média.' },
  // ACORDES
  { id: 'acorde', termo: 'Acorde', termoIngles: 'Chord', nivel: 'iniciante', categoria: 'acordes', definicaoSimples: 'Três ou mais notas tocadas ao mesmo tempo.', definicaoCompleta: 'Sobreposição de notas. Tríades = 3, tétrades = 4. Tem fundamental, qualidade e posição.', exemplos: ['C = C+E+G', 'Am = A+C+E', 'G7 = G+B+D+F'], termosRelacionados: ['triade', 'tetrade', 'fundamental'], tooltipTexto: '3+ notas tocadas simultaneamente' },
  { id: 'triade', termo: 'Tríade', termoIngles: 'Triad', nivel: 'iniciante', categoria: 'acordes', definicaoSimples: 'Acorde de 3 notas: fundamental, 3ª e 5ª.', definicaoCompleta: '4 tipos: maior (3M+5J), menor (3m+5J), diminuta (3m+5d), aumentada (3M+5A).', exemplos: ['C: C-E-G', 'Am: A-C-E', 'Bdim: B-D-F'], termosRelacionados: ['fundamental', 'terca', 'quinta'], tooltipTexto: 'Acorde de 3 notas (fundamental + 3ª + 5ª)' },
  { id: 'tetrade', termo: 'Tétrade', termoIngles: 'Seventh chord', nivel: 'iniciante', categoria: 'acordes', definicaoSimples: 'Acorde de 4 notas: tríade + 7ª. Base do jazz.', definicaoCompleta: 'Principais: dom7 (1-3-5-7b), m7 (1-3b-5-7b), maj7 (1-3-5-7), dim7 (1-3b-5b-7bb).', exemplos: ['Cmaj7: C-E-G-B', 'G7: G-B-D-F', 'Dm7: D-F-A-C'], termosRelacionados: ['triade', 'setima'], tooltipTexto: 'Acorde de 4 notas (tríade + 7ª)' },
  { id: 'fundamental', termo: 'Fundamental', termoIngles: 'Root', nivel: 'iniciante', categoria: 'acordes', definicaoSimples: 'A nota que dá o nome ao acorde.', definicaoCompleta: 'Nota base sobre a qual o acorde é construído. Não precisa ser a nota mais grave (em inversões).', exemplos: ['Em Cmaj7: C', 'Em G7/F: G (F está no baixo)'], termosRelacionados: ['inversao', 'acorde'], tooltipTexto: 'Nota que dá o nome ao acorde' },
  { id: 'inversao', termo: 'Inversão', termoIngles: 'Inversion', nivel: 'intermediario', categoria: 'acordes', definicaoSimples: 'Quando uma nota diferente da fundamental fica no baixo.', definicaoCompleta: '1ª inversão = 3ª no baixo. 2ª = 5ª. 3ª = 7ª (tétrades). Cria movimento suave.', exemplos: ['C/E = 1ª inversão', 'C/G = 2ª', 'G7/F = 3ª'], termosRelacionados: ['fundamental', 'slash-chord'], tooltipTexto: 'Nota diferente da fundamental no baixo', curiosidade: 'A 1ª inversão é muito usada em linhas de baixo diatônicas.' },
  { id: 'voicing', termo: 'Voicing', nivel: 'intermediario', categoria: 'acordes', definicaoSimples: 'A disposição das notas de um acorde nos registros.', definicaoCompleta: 'Close (compacto), open (espalhado), drop 2, rootless (sem fundamental), quartal (por quartas).', exemplos: ['Close: C3-E3-G3-B3', 'Drop2: C3-G3-B3-E4'], termosRelacionados: ['inversao'], tooltipTexto: 'Disposição das notas nos registros' },
  { id: 'extensao', termo: 'Extensão', termoIngles: 'Extension', nivel: 'intermediario', categoria: 'acordes', definicaoSimples: 'Notas além da 7ª: 9ª, 11ª e 13ª.', definicaoCompleta: '9ª = 2ª oitava acima, 11ª = 4ª, 13ª = 6ª. Podem ser naturais ou alteradas (b9, #11).', exemplos: ['C9: C-E-G-Bb-D', 'Cmaj9: C-E-G-B-D'], termosRelacionados: ['setima', 'tetrade'], tooltipTexto: '9ª, 11ª e 13ª adicionadas além da 7ª' },
  // FUNÇÃO HARMÔNICA
  { id: 'tonica', termo: 'Tônica', termoIngles: 'Tonic', nivel: 'intermediario', categoria: 'funcao-harmonica', definicaoSimples: 'Acorde de repouso — onde a música se sente em casa.', definicaoCompleta: 'Centro tonal. Graus I, III e VI. O I é a tônica principal.', exemplos: ['Em C: C(I), Em(III), Am(VI) = tônica'], termosRelacionados: ['dominante', 'subdominante', 'campo-harmonico'], tooltipTexto: 'Função de repouso harmônico (I, III, VI)' },
  { id: 'dominante', termo: 'Dominante', termoIngles: 'Dominant', nivel: 'intermediario', categoria: 'funcao-harmonica', definicaoSimples: 'Acorde de máxima tensão — quer resolver para a tônica.', definicaoCompleta: 'Grau V7 e VII. V7 contém trítono interno. Cria tensão irresistível.', exemplos: ['Em C: G7(V) = dominante', 'G7→C = cadência perfeita'], termosRelacionados: ['tonica', 'tritono', 'cadencia'], tooltipTexto: 'Máxima tensão, resolve na tônica (V, VII)', curiosidade: 'Sem dominante, não há tonalidade.' },
  { id: 'subdominante', termo: 'Subdominante', termoIngles: 'Subdominant', nivel: 'intermediario', categoria: 'funcao-harmonica', definicaoSimples: 'Tensão média — leva da tônica ao dominante.', definicaoCompleta: 'Graus II e IV. IIm7 é o preferido no jazz pela suavidade.', exemplos: ['Em C: F(IV), Dm(II) = subdominante'], termosRelacionados: ['tonica', 'dominante'], tooltipTexto: 'Tensão média entre T e D (II, IV)' },
  { id: 'campo-harmonico', termo: 'Campo Harmônico', nivel: 'intermediario', categoria: 'funcao-harmonica', definicaoSimples: 'Os 7 acordes que pertencem a uma tonalidade.', definicaoCompleta: 'Acordes formados só com notas da escala. Em C: C-Dm-Em-F-G7-Am-Bdim.', exemplos: ['C maior: C-Dm-Em-F-G7-Am-Bdim'], termosRelacionados: ['tonica', 'dominante', 'subdominante'], tooltipTexto: '7 acordes que pertencem a uma tonalidade' },
  { id: 'cadencia', termo: 'Cadência', termoIngles: 'Cadence', nivel: 'intermediario', categoria: 'funcao-harmonica', definicaoSimples: 'Sequência de acordes que cria conclusão ou pausa.', definicaoCompleta: 'Autêntica (V→I), Plagal (IV→I), Half (→V), Deceptiva (V→VI).', exemplos: ['Autêntica: G7→C', 'Plagal: F→C ("amém")'], termosRelacionados: ['dominante', 'tonica', 'ii-v-i'], tooltipTexto: 'Progressão que cria repouso ou suspensão' },
  { id: 'ii-v-i', termo: 'II-V-I', nivel: 'intermediario', categoria: 'funcao-harmonica', definicaoSimples: 'A progressão mais importante do jazz: SD→D→T.', definicaoCompleta: 'Dm7→G7→Cmaj7. O II prepara o V, o V resolve no I. Base do jazz.', exemplos: ['Dm7→G7→Cmaj7'], exemplosMusicas: ['Autumn Leaves', 'Fly Me to the Moon'], termosRelacionados: ['cadencia', 'dominante'], tooltipTexto: 'Cadência fundamental do jazz: SD→D→T', curiosidade: 'Aparece em quase todas as músicas de jazz.' },
  // ESCALAS
  { id: 'escala-cromatica', termo: 'Escala Cromática', nivel: 'iniciante', categoria: 'escalas', definicaoSimples: 'Todas as 12 notas em sequência, cada uma a 1 semitom.', definicaoCompleta: 'Base de todas as escalas. Inclui todas as notas naturais e alteradas.', exemplos: ['C-C#-D-D#-E-F-F#-G-G#-A-A#-B'], termosRelacionados: ['semitom', 'nota'], tooltipTexto: '12 notas, cada uma a 1 semitom da próxima' },
  { id: 'modo', termo: 'Modo', termoIngles: 'Mode', nivel: 'avancado', categoria: 'escalas', definicaoSimples: 'Escala derivada da maior, começando em grau diferente.', definicaoCompleta: '7 modos gregos: Jônio(I), Dórico(II), Frígio(III), Lídio(IV), Mixolídio(V), Eólio(VI), Lócrio(VII).', exemplos: ['Dórico: D-E-F-G-A-B-C', 'Mixolídio: G-A-B-C-D-E-F'], termosRelacionados: ['campo-harmonico'], tooltipTexto: 'Escala derivada da maior, iniciando em grau diferente', curiosidade: 'O Dórico é o favorito do jazz e blues.' },
  // AVANÇADO
  { id: 'substituicao-tritono', termo: 'Substituição do Trítono', nivel: 'avancado', categoria: 'teoria-avancada', definicaoSimples: 'Trocar o dominante por outro a 6 semitons.', definicaoCompleta: 'G7→Db7. Compartilham trítono (B-F). Cria resolução cromática elegante.', exemplos: ['G7→Db7 (substituto)'], termosRelacionados: ['tritono', 'dominante'], tooltipTexto: 'V7 substituído por dominante a 6 semitons', curiosidade: 'Charlie Parker era mestre no "sub V".' },
  { id: 'rearmonizacao', termo: 'Rearmonização', nivel: 'avancado', categoria: 'teoria-avancada', definicaoSimples: 'Criar nova harmonia para uma melodia existente.', definicaoCompleta: 'Técnicas: trítono, empréstimo modal, dominantes secundários, poliacordes, harmonia negativa.', exemplos: ['V7→subV7', 'Adicionar IIm7 antes de cada V7'], termosRelacionados: ['substituicao-tritono', 'modal-interchange'], tooltipTexto: 'Arte de criar nova harmonia para melodia existente' },
  { id: 'modal-interchange', termo: 'Intercâmbio Modal', nivel: 'avancado', categoria: 'teoria-avancada', definicaoSimples: 'Emprestar acordes de um modo paralelo.', definicaoCompleta: 'Em C maior, usar Fm (IVm do menor). Cria contraste cromático e emocional.', exemplos: ['Fm em C maior (IVm)', 'Bb em C (bVII do mixolídio)'], exemplosMusicas: ['Yesterday', 'No Surprises'], termosRelacionados: ['modo', 'rearmonizacao'], tooltipTexto: 'Acordes emprestados de um modo paralelo' },
  { id: 'poliacorde', termo: 'Poliacorde', nivel: 'avancado', categoria: 'teoria-avancada', definicaoSimples: 'Dois acordes tocados simultaneamente.', definicaoCompleta: 'Ex: F#/C = Cmaj7#11. Cria sons complexos do jazz avançado e gospel.', exemplos: ['F#/C = Cmaj7#11', 'Bb/C = C11sus'], termosRelacionados: ['extensao', 'voicing'], tooltipTexto: 'Dois acordes soando simultaneamente' },
  // ESTILOS
  { id: 'jazz', termo: 'Jazz', nivel: 'iniciante', categoria: 'estilos', definicaoSimples: 'Estilo americano com extensões, improvisação e swing.', definicaoCompleta: 'Mistura de blues, ragtime e música europeia. Usa tétrades+, II-V-I, swing e improvisação.', exemplos: ['Bebop', 'Hard bop', 'Modal jazz'], exemplosMusicas: ['So What', 'Autumn Leaves'], termosRelacionados: ['ii-v-i', 'extensao'], tooltipTexto: 'Estilo com extensões, improvisação e swing' },
  { id: 'gospel', termo: 'Gospel', nivel: 'iniciante', categoria: 'estilos', definicaoSimples: 'Música cristã com harmonia rica e emoção intensa.', definicaoCompleta: 'Acordes ricos (maj7, m7, 9, 11, 13), voicings densos, cromatismos e expressividade.', exemplos: ['Cmaj9, Am7, Em7', 'Cromatisnmo no baixo'], termosRelacionados: ['extensao', 'voicing'], tooltipTexto: 'Música cristã com harmonia rica e extensões' },
  { id: 'slash-chord', termo: 'Slash Chord', nivel: 'intermediario', categoria: 'acordes', definicaoSimples: 'Notação X/Y = acorde X com nota Y no baixo.', definicaoCompleta: 'C/E = C com Mi no baixo (1ª inversão). Pode ser inversão ou pedal.', exemplos: ['C/E = 1ª inversão', 'F/C = com Dó pedal'], termosRelacionados: ['inversao', 'fundamental'], tooltipTexto: 'X/Y = acorde X com nota Y no baixo' },
];

export const GLOSSARIO_POR_ID = Object.fromEntries(GLOSSARIO.map((t) => [t.id, t]));

export const NOMES_CATEGORIAS: Record<CategoriaGlossario, string> = {
  'notas-basicas': '🎵 Notas e Básicos', 'intervalos': '📏 Intervalos', 'acordes': '🎹 Acordes',
  'funcao-harmonica': '🎼 Função Harmônica', 'escalas': '🎶 Escalas e Modos',
  'estilos': '🎷 Estilos Musicais', 'teoria-avancada': '🔬 Teoria Avançada',
};
